services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    user: "www-data"
    ports:
      - "82:80"
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      TZ: Europe/Paris
      DATABASE_URL: "mysql://root:root@db:3306/project_docker?serverVersion=8.0"
      MAILER_DSN: "smtp://mailhog:1025"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_docker
      TZ: Europe/Paris
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
    restart: unless-stopped
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: symfony_pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
      TZ: Europe/Paris
    ports:
      - "8888:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - symfony

  mailhog:
    image: mailhog/mailhog:latest
    container_name: symfony_mailhog
    ports:
      - "8025:8025"
    restart: unless-stopped
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
 